library(dplyr)
library(caret)
library(readxl)
df<-student_scores_student_scores
head(df)
dim(df)
ggplot(df,aes(x=Hours,y=Scores))+geom_point()
#spliting
set.seed(42)
rows<-sample(nrow(df))
shuffled_df<-df[rows,]
split<-round(nrow(df)*0.6)
train<-df[1:split,]
test<-df[split+1:nrow(df),]
#modeling
model<-lm(Scores~Hours,train)
plot(Scores~Hours,data=df)
abline(model)
summary(model)
p<-predict(model,test)
p
p<-p[1:10]
test<-test[1:10,]
predict(model,list(Hours=9.5))
